### PR TITLE
adding new application loadbalancer objects and properties, following AWS announcement https://a…

### PR DESCRIPTION
**Pull request by axelpavageau**
https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/

### CODE REVIEW

**Comment by philtay** [comment]
Please also add the `TargetGroupARNs` property to `AWS::AutoScaling::AutoScalingGroup` in order to complete this PR as per `August 11, 2016` [CloudFormation release](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html). Thanks a lot!

**Comment by philtay** [comment]
Also note that I have created a separated module for `AWS::ApplicationAutoScaling`. I mean, now in troposphere we have both `autoscaling` and `applicationautoscaling` modules. This PR, instead, includes both `AWS::ElasticLoadBalancingV2` and `AWS::ElasticLoadBalancing` in the same module. The natural name of the class for `AWS::ElasticLoadBalancingV2::LoadBalancer` would be `LoadBalancer` but you had to name it `ApplicationLoadBalancer` in order to avoid clashing with the already existing `AWS::ElasticLoadBalancing::LoadBalancer`. Basically I suggest to use separate modules for these resources too, but I think it's up to @markpeek to decide. I'm ready to merge `autoscaling` and `applicationautoscaling` if Mark wants me to.

**Comment by axelpavageau** [comment]
You're right, it makes more sense to create a separate module. I hesitated between both options and went for a single module, but after a bit of sleep your way seems better. 
The object's names will be more consistent with AWS'.
I'll correct my PR

**Comment by philtay** [comment]
LGTM

**Comment by ntwaddell** [comment]
Awesome, thanks for getting this added so quickly.  :D

**Comment by markpeek** [comment]
Thanks! Appreciate the rework and adding the example.

**Comment by mitesh9875** [comment]
Hi, 
I have not get any example to setup application ELB, please share example for application loadbalancer.

**Comment by phobologic** [comment]
@mitesh9875 The example troposphere code and the resulting cloudformation template are both included in this pull request.  You can find them in the `examples` directory as well.

https://github.com/cloudtools/troposphere/blob/master/examples/ApplicationELB.py

**Pull request merged**
