### PR TITLE
Adding new properties to elbv2 Listener Action

### LINKED ISSUE #1240: Add support new for ElasticLoadBalancingV2::Listener Action properties
CloudFormation's ALB Listener Action documentation now includes several additional properties not yet supported by troposphere:

```
{
  "AuthenticateCognitoConfig" : AuthenticateCognitoConfig,
  "AuthenticateOidcConfig" : AuthenticateOidcConfig,
  "FixedResponseConfig" : FixedResponseConfig,
  "Order" : Integer,
  "RedirectConfig" : RedirectConfig,
  "TargetGroupArn" : String,
  "Type" : String
}
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-defaultactions.html

Please add support for these properties. Thanks!

### PR DESCRIPTION
**Pull request by dgouldin**
* AuthenticateCognitoConfig
 * AuthenticateOidcConfig
 * FixedResponseConfig
 * Order
 * RedirectConfig

Resolves #1240

### CODE REVIEW

**Comment by dgouldin** [comment]
The documentation is wrong. I've added a commit to reflect the fact that TargetGroupArn is no longer required.

**Comment by dgouldin** [comment]
May be a duplicate of https://github.com/cloudtools/troposphere/pull/1140

**Comment by markpeek** [comment]
Implemented via merge of #1140. Thanks for the PR.

**Comment by markpeek** [comment]
Via the mailing list it was noted that the merge of #1140 did not include AuthenticateCognitoConfig or AuthenticateOidcConfig. I just merged those in from the PR. Thanks!

**Pull request closed without merging**
