### PR TITLE
Release June 11, 2015

### PR DESCRIPTION
**Pull request by philtay**
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/DocumentHistory.html

### CODE REVIEW

**Comment by phobologic** [comment]
@philtay you are a cloudformation machine :)

**Comment by philtay** [comment]
:D

**Comment by philtay** [comment]
The last commit (S3 Lifecycle Rule) is documented [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html).

**Comment by markpeek** [comment]
Awesome! Thanks for jumping on the new release with this pull request. We'll roll a release over the weekend to include them into a release build.

**Comment by bobveznat** [comment]
Like a boss! On behalf of troposphere users across the world, thanks @philtay !

**Pull request merged**
