### PR TITLE
add Condition parse feature to cfn2py script

### PR DESCRIPTION
**Pull request by williamjoy**
parse template json condition sections

### CODE REVIEW

**Comment by ldenman** [comment]
Nice, I can play around with this soon and see if it works for my case.

**Comment by ldenman** [comment]
INPUT.JSON:
```
{
    "Description" : "Foo Bar",
    "Resources" : { },

    "Parameters" : {
        "EnvironmentType" : {
            "Description" : "Resource sizes and settings differ based on environment",
            "Type" : "String",
            "Default" : "dev",
            "AllowedValues" : [ "dev", "stag", "prod"],
            "ConstraintDescription" : "choose one of allowed types."
        }
    },
    "Conditions" : {
        "UseDevSettings" : {"Fn::Equals": [{"Ref": "EnvironmentType"}, "dev"]},
        "UseStagSettings" : {"Fn::Equals": [{"Ref": "EnvironmentType"}, "stag"]},
        "UseProdSettings" : {"Fn::Equals": [{"Ref": "EnvironmentType"}, "prod"]}
    },

    "Outputs" : {
    }
}
```
BEFORE #PR351
```
from troposphere import Base64, Select, FindInMap, GetAtt, GetAZs, Join, Output
from troposphere import Parameter, Ref, Tags, Template
from troposphere.cloudformation import Init
from troposphere.cloudfront import Distribution, DistributionConfig
from troposphere.cloudfront import Origin, DefaultCacheBehavior
from troposphere.ec2 import PortRange


t = Template()

t.add_description("""\
Foo Bar""")
EnvironmentType = t.add_parameter(Parameter(
    "EnvironmentType",
    Default="dev",
    ConstraintDescription="choose one of allowed types.",
    Type="String",
    Description="Resource sizes and settings differ based on environment",
    AllowedValues=["dev", "stag", "prod"],
))

print(t.to_json())
```



AFTER #PR351 OUTPUT:
```
from troposphere import Base64, Select, FindInMap, GetAtt, GetAZs, Join, Output
from troposphere import Parameter, Ref, Tags, Template, Not, Equals, And, Or, If
from troposphere.cloudformation import Init
from troposphere.cloudfront import Distribution, DistributionConfig
from troposphere.cloudfront import Origin, DefaultCacheBehavior
from troposphere.ec2 import PortRange


t = Template()

t.add_description("""\
Foo Bar""")
EnvironmentType = t.add_parameter(Parameter(
    "EnvironmentType",
    Default="dev",
    ConstraintDescription="choose one of allowed types.",
    Type="String",
    Description="Resource sizes and settings differ based on environment",
    AllowedValues=["dev", "stag", "prod"],
))

t.add_condition("UseStagSettings", Equals(Ref(EnvironmentType), stag) )

t.add_condition("UseProdSettings", Equals(Ref(EnvironmentType), prod) )

t.add_condition("UseDevSettings", Equals(Ref(EnvironmentType), dev) )

print(t.to_json())
```

**Comment by ldenman** [comment]
Notice in the last file listed, the third argument to the add_condition method is stag, prod, or dev. I expected those to be printed as string literals since they are strings in the input. I may have time to look further into this over the weekend.

**Comment by martinb3** [comment]
I'd love to see this merged. Let us know if we can help test! 👍

**Comment by williamjoy** [comment]
now quotes string!
```json
{
    "Description" : "Foo Bar",
    "Resources" : { },

    "Parameters" : {
        "EnvironmentType" : {
            "Description" : "Resource sizes and settings differ based on environment",
            "Type" : "String",
            "Default" : "dev",
            "AllowedValues" : ["test", "dev", "stag", "prod"],
            "ConstraintDescription" : "choose one of allowed types."
        }
    },
    "Conditions" : {
        "UseDevSettings" : {"Fn::Equals": [{"Ref": "EnvironmentType"}, "dev"]},
        "UseStagSettings" : {"Fn::Equals": [{"Ref": "EnvironmentType"}, "stag"]},
        "UseProdSettings" : {"Fn::Equals": [{"Ref": "EnvironmentType"}, "prod"]},
        "UsecTestSettings" : {"Fn::Equals": ["test" , {"Ref": "EnvironmentType"}]}
    },

    "Outputs" : {
    }
}
```

scripts/cfn2py  x.json 
```python
from troposphere import Base64, Select, FindInMap, GetAtt, GetAZs, Join, Output
from troposphere import Parameter, Ref, Tags, Template, Not, Equals, And, Or, If
from troposphere.cloudformation import Init
from troposphere.cloudfront import Distribution, DistributionConfig
from troposphere.cloudfront import Origin, DefaultCacheBehavior
from troposphere.ec2 import PortRange


t = Template()

t.add_description("""\
Foo Bar""")
EnvironmentType = t.add_parameter(Parameter(
    "EnvironmentType",
    Default="dev",
    ConstraintDescription="choose one of allowed types.",
    Type="String",
    Description="Resource sizes and settings differ based on environment",
    AllowedValues=["test", "dev", "stag", "prod"],
))

t.add_condition("UseStagSettings", Equals(Ref(EnvironmentType), "stag") )

t.add_condition("UseProdSettings", Equals(Ref(EnvironmentType), "prod") )

t.add_condition("UseDevSettings", Equals(Ref(EnvironmentType), "dev") )

t.add_condition("UsecTestSettings", Equals("test", Ref(EnvironmentType)) )

print(t.to_json())
```

**Comment by williamjoy** [comment]
Hi, could this be merged now ?

**Pull request closed without merging**
