### PR TITLE
Add NLB Functionality

### PR DESCRIPTION
**Pull request by DanHoerst**

### CODE REVIEW

**Comment by DanHoerst** [comment]
Closing. Just saw someone beat me to it.

**Comment by DanHoerst** [comment]
@cwgem Reopened this as https://github.com/cloudtools/troposphere/pull/804 was closed

**Comment by alangarf** [comment]
Any chance this will be merged soon? This is kinda holding up a bunch of stuff for us. Happy to lend assistance where I can.

**Comment by oussemos** [comment]
:+1: waiting for this to be merged :pray:

**Comment by DanHoerst** [comment]
If there's more that needs to be added to this let me know. I'm under the impression that this is ready.

**Comment by markpeek** [comment]
Thanks! Sorry for the delay as I've been traveling the past couple weeks.

**Comment by oussemos** [comment]
Time for a new release :smiley:

**Comment by markpeek** [comment]
Fixes #805

**Pull request merged**
