### PR TITLE
Provide Valid Lambda Function Memory Values for use in Parameters

### PR DESCRIPTION
**Pull request by ink-adavison**
Lambda functions can only have certain amounts of memory in multiples of 64
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-memorysize

This commit allows MEMORY_VALUES to be used against Parameters' AllowedValues attribute, so that the Cloudformation web console form has a drop down selection of memory values in the same way it currently is in the Lambda web console.

I've updated the Lambda example to demonstrate.

I'm aware this could become unwieldy if AWS increase the amounts of memory available to Lambda functions, but if that occurs, this could be reverted or compared with any UI changes in the Lambda web console.

### CODE REVIEW

**Comment by phobologic** [comment]
Thanks @ink-adavison - do you think it'd be worth updating the validator for https://github.com/cloudtools/troposphere/blob/master/troposphere/awslambda.py#L53 ?

**Comment by ink-adavison** [comment]
Like this? I've tested it against AWS helper functions (Ref, If), valid number strings, invalid number strings, actual text strings, booleans, valid and invalid numbers. Looks like it works as intended.

**Comment by phobologic** [comment]
Sorry for the delay @ink-adavison - this looks great.  There are conflicts now - can you fix those and we'll merge ASAP?

**Comment by ink-adavison** [comment]
ack I really messed that up, let me revert a load of this and try again

**Comment by ink-adavison** [comment]
Sorry, this is so messed up I'm just going to nuke it and start again with a new pull request.

**Pull request closed without merging**
