### PR TITLE
Update list of valid Synthetics::Canary runtime versions

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by markpeek** [comment]
Thank you for the PR. I noticed [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library.html#CloudWatch_Synthetics_Canaries_runtime_support) that some of these were deprecated on March 8, 2024. Could you remove the deprecated ones and resubmit?

**Comment by sir-sigurd** [comment]
> Thank you for the PR. I noticed [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library.html#CloudWatch_Synthetics_Canaries_runtime_support) that some of these were deprecated on March 8, 2024. Could you remove the deprecated ones and resubmit?

well, though they're deprecated I'm not sure you can't create create, update or use them

e.g. `python3.8` lambda was deprecated on Oct 14 but you still can create it till Feb 28, update till Mar 31 and I don't think AWS is going to remove existing lambdas

**Comment by markpeek** [comment]
Ahhh, got it. Thank you for the clarification. We'll leave them alone for now.

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
