### PR TITLE
recommended soft dependency

### PR DESCRIPTION
**Pull request by philtay**
`pip install troposphere[policy]` will install troposphere + awacs

### CODE REVIEW

**Comment by phobologic** [comment]
Awesome, thanks!

**Comment by hammadzz** [comment]
How does this work? Do I insert something in policy? As it is, it does not work for me on pip 9.0.1

**Comment by philtay** [comment]
@hammadzz run the following command in your terminal:

```$ pip install troposphere[policy]```

`pip` will install both `troposphere` and `awacs`.

**Comment by hammadzz** [comment]
@philtay which pip version does that command work on? Does not work on pip 9.0.1

**Comment by philtay** [comment]
@hammadzz it works on pip 9.0.1, I just tried. This is standard pip / setuptools feature. Google for `pip extras_require` to find out more.

**Pull request merged**
