### PR TITLE
Cloudformation expects a string as a FilterPatter

### PR DESCRIPTION
**Pull request by urtens**
Cloudformation expects a string as a FilterPatter

### CODE REVIEW

**Comment by markpeek** [comment]
Will have to investigate as the docs say "A list of strings".

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-metricfilter.html

**Comment by urtens** [comment]
You're right. It might be an outdated documentation though. CloudFormation spits out an error if you pass a list of strings:
"AWS::Logs::MetricFilter" "Value of property FilterPattern must be of type String"

**Comment by jorgebastida** [comment]
Hitting this issue too. It is true that the documentation say that ``FilterPattern`` but their examples http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudwatchlogs.html use strings and not lists of strings.

Tested this PR and CloudFormation is happy with the output. :+1:

**Comment by markpeek** [comment]
Merged. Thank you @urtens for the fix and @jorgebastida for the confirmation.

**Pull request merged**
