### PR TITLE
Add `cfn_flip` to install_requires again

### PR DESCRIPTION
**Pull request by michael-k**
Fixes cloudtools/troposphere#1926

### CODE REVIEW

**Comment by michael-k** [comment]
We could also make it an optional dependency.

1. Add `yaml = cfn_flip>=1.0.2` to `[options.extras_require]` in `setup.cfg`
2. Add a try-except around [`import cfn_flip`](https://github.com/cloudtools/troposphere/blob/a3a87a258a3f46371b1be54340f236d30e5d06db/troposphere/__init__.py#L11).
3. Raise an exception in [`def to_yaml()`](https://github.com/cloudtools/troposphere/blob/a3a87a258a3f46371b1be54340f236d30e5d06db/troposphere/__init__.py#L773-L776) that explains that `troposphere[yaml]` should be installed for YAML support.

But I think YAML is widely used and it's worth always installing it.  Any other opinions?  Any data on JSON vs. YAML for CloudFormation?

**Comment by markpeek** [comment]
Fixed via #1927, added a test to catch in "make release-test", and released 3.0.1. Thanks for the fix though. yaml seems popular enough to make it a mandatory requirement.

**Comment by michael-k** [comment]
Didn't see that one as it didn't link the issue :shrug:

**Comment by jerry153fish** [comment]
Sorry about that forget to link the issue as I had the fixes then I replied in the issue.

**Pull request closed without merging**
