### PR TITLE
Added UsagePlans to API Gateway example

### PR DESCRIPTION
**Pull request by V3ckt0r**
This pull request is simply to include Usage Plans into the example provided.

### CODE REVIEW

**Comment by V3ckt0r** [comment]
[Python 2.7](https://travis-ci.org/cloudtools/troposphere/builds/242528616) - "Y u no pass!". Gotta shoot now. Someone give it an eye ball please.

**Comment by markpeek** [comment]
The template containing the correct output needs to put added as well [here](https://github.com/cloudtools/troposphere/blob/master/tests/examples_output/ApiGateway.template).

**Comment by V3ckt0r** [comment]
Thanks dude, this one is ready to go.

**Comment by V3ckt0r** [comment]
hold that thought... Don't merge yet. As it stands this example is not linking the key with the usage plan. You would probably want to do that ^_^. Pushing that into PR.

**Comment by V3ckt0r** [comment]
btw - ready for review

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
