### PR TITLE
Release 2.6.4

### PR DESCRIPTION
**Pull request by svsShiva**
Release new version with fix for issue regarding efs volume (https://github.com/cloudtools/troposphere/issues/1806). 

fixes https://github.com/cloudtools/troposphere/issues/1831

### CODE REVIEW

**Comment by zbrookle** [comment]
@svsShiva Is this release planned to occur soon? There are some updates that my team needs to awslambda from back in November, so it would be great to have those in released version of the package

**Comment by JohnPreston** [comment]
Hello @markpeek @PatMyron 
Any updates on when we can get 2.6.4 release in pypi ? Seems like a number of projects are waiting for that release to make their own.
Given this is a patch release (unless 2.7.0 or 3.0 is more imminent) can we get this out sooner than later?
Many thanks!

**Comment by sir-sigurd** [comment]
2.6.4 was released:
https://github.com/cloudtools/troposphere/releases/tag/2.6.4
https://pypi.org/project/troposphere/2.6.4/

**Comment by markpeek** [comment]
As noted, 2.6.4 was released on 2021-03-08. Look for upcoming releases:
- Will do a catchup release 2.7.0 which will be the final Python 2.x release
- Then switch the code to Python 3.x only for a 3.0.0 release.

**Pull request closed without merging**
