### PR TITLE
Support "UserName" property for AWS::IAM::User

### PR DESCRIPTION
**Pull request by dmm92**
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html#cfn-iam-user-username

### CODE REVIEW

**Comment by markpeek** [comment]
This looks good. It would be good to validate the length not being the empty string explicitly. Also, some positive/negative tests for the length and regex would be a welcome addition.

**Comment by dmm92** [comment]
@markpeek is troposphere moving towards doing its own validation? In most places it is 'dumb' and has AWS do the validation. I was hesitant to even add validation as a result — what's the pattern? Is there a plan to gradually add validators for everything? If not I think it would be better to leave them out entirely

**Comment by markpeek** [comment]
Besides being able to write templates in Python, the original intent for troposphere was to do as much validation at template generation time as possible to prevent having CF rollbacks from occurring. You're right, not everything is validated but there are both base and custom validators available and I'd welcome people contributing more validation. To the point of my comment, since you had some validation (length of string, regex) I thought it would be good to catch an empty string and also add tests to ensure the correct behavior was occurring.

**Comment by markpeek** [comment]
Thanks. I added the empty string check and some unit tests in the above commit.

**Comment by dmm92** [comment]
@markpeek Thanks! Sorry I didn't get to this before I went on vacation

**Pull request merged**
