### PR TITLE
Added postgresql-license. Closes #323

### LINKED ISSUE #323: RDS ValueError on LicenseModel
I'm hitting a similar problem to #316, Postgres instances only use the string `'postgresql-license'` for the LicenseModel parameter and I'm getting a ValueError:
```
ValueError: DBInstance LicenseModel must be one of: license-included, bring-your-own-license, general-public-license
```
I could not find the `postgresql-license` in any API documentation, but it is in the [user-guide](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreatePostgreSQLInstance.html)

### PR DESCRIPTION
**Pull request by micahhausler**

### CODE REVIEW

**Comment by phobologic** [comment]
:+1:

**Comment by phobologic** [comment]
I wonder if we should look at the MYSQL license models as well.  These non-documented features are a PITA.

**Comment by micahhausler** [comment]
Couldn't agree more: Looks like MySQL is in the clear from the [user-guide](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreateInstance.html)

**Comment by micahhausler** [comment]
Is there anything else to add to this?

**Comment by micahhausler** [comment]
The MySQL license uses the license `general-public-license`, is this good to merge?

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
