### PR TITLE
adding better validation for AWS::CloudWatch::Alarm properties

### PR DESCRIPTION
**Pull request by axelpavageau**

### CODE REVIEW

**Comment by markpeek** [comment]
@girishkhadke what you seem to be implying is Metric, Statistic, and ExtendedStatistic are all mutually exclusive. So should the validate be implemented as:
```
def validate(self):
        conds = [
            'ExtendedStatistic',
            'Metric',
            'Statistic',
        ]
        exactly_one(self.__class__.__name__, self.properties, conds)
```

**Comment by axelpavageau** [comment]
I've updated the PR, but I believe the cloudformation attribute is `MetricName` not `Metric` ?

**Comment by girishkhadke** [comment]
According to AWS documentation, the name of attribute used to specify a metric based on math expression is : "Metrics" 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarm-metrics

**Comment by girishkhadke** [comment]
This is the error I was getting on Cloudformation Stack create/update:

```
Statistic should not be set if list of Metrics is set. (Service: AmazonCloudWatch; Status Code: 400; Error Code: ValidationError; Request ID: *****)
```

**Comment by axelpavageau** [comment]
allright. I've updated the PR.

**Comment by markpeek** [comment]
Thanks for the quick turnaround on a fix.

**Comment by girishkhadke** [comment]
Thank you.

**Pull request merged**
