### PR TITLE
updating AWS::CloudWatch::Alarm, per Nov 20 2018 update

### PR DESCRIPTION
**Pull request by axelpavageau**

### CODE REVIEW

**Comment by markpeek** [comment]
Thanks!

**Comment by girishkhadke** [comment]
Is this available as part of 2.3.4 troposphere version ?

I have following installed in my python virtualenvironment:

(ebansible) M117553F2G8WP:ansible girish_khadke$ pip freeze | grep boto
boto==2.49.0
boto3==1.9.71
botocore==1.12.71
(ebansible) M117553F2G8WP:ansible girish_khadke$ pip freeze | grep awscli
awscli==1.16.81
(ebansible) M117553F2G8WP:ansible girish_khadke$ pip freeze | grep troposphere
troposphere==2.3.4

But still I get following error when I try to generate CFN template (yaml) using troposphere:

`
        "Traceback (most recent call last):", 
        "  File \"./vip_oidc_dynamo_alarms_cfn.py\", line 8, in <module>", 
        "    def run(description=\"DynamoDB Regional Alarms Stack for tables related to VIP OIDC Application\"):", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/main.py\", line 115, in _start", 
        "    prog.start()", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/main.py\", line 54, in start", 
        "    collector=self._collector)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/cmdline.py\", line 253, in apply_options", 
        "    return_value = call_function(func, signature(ext), opts)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/cmdline.py\", line 236, in call_function", 
        "    return func(*pargs, **kwargs)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/convert.py\", line 92, in wrapper", 
        "    return func(*args, **kwargs)", 
        "  File \"./vip_oidc_dynamo_alarms_cfn.py\", line 9, in run", 
        "    dynamo_alarms.run(description=description)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/wrappable.py\", line 20, in __call__", 
        "    return self.__wrapped__(*args, **kwargs)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/convert.py\", line 92, in wrapper", 
        "    return func(*args, **kwargs)", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 213, in run", 
        "    template = VipOidcDynamoDbAlarmsTemplate(Description=description)", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 21, in __init__", 
        "    self.build()", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 208, in build", 
        "    self.build_resources();", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 146, in build_resources", 
        "    cloudwatch.MetricDataQuery(", 
        "AttributeError: 'module' object has no attribute 'MetricDataQuery'"
`

**Comment by seddarj** [comment]
@girishkhadke This was merged on December 23rd but 2.3.4 came out some time in November so we'll have to wait until 2.3.5 is released to use this feature.

**Comment by girishkhadke** [comment]
Thank you for reply.

**Comment by markpeek** [comment]
BTW, released in 2.4.0 yesterday.

**Comment by girishkhadke** [comment]
Thank you.  But it kind of left one bug which makes this functionality unusable:

stderr_lines": [
        "Traceback (most recent call last):", 
        "  File \"./vip_oidc_dynamo_alarms_cfn.py\", line 8, in <module>", 
        "    def run(description=\"DynamoDB Alarms stack for VIP OIDC Application\"):", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/main.py\", line 115, in _start", 
        "    prog.start()", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/main.py\", line 54, in start", 
        "    collector=self._collector)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/cmdline.py\", line 253, in apply_options", 
        "    return_value = call_function(func, signature(ext), opts)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/cmdline.py\", line 236, in call_function", 
        "    return func(*pargs, **kwargs)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/convert.py\", line 92, in wrapper", 
        "    return func(*args, **kwargs)", 
        "  File \"./vip_oidc_dynamo_alarms_cfn.py\", line 9, in run", 
        "    oidc_dynamo_alarms.run(description=description)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/wrappable.py\", line 20, in __call__", 
        "    return self.__wrapped__(*args, **kwargs)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/convert.py\", line 92, in wrapper", 
        "    return func(*args, **kwargs)", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 714, in run", 
        "    print(template.to_yaml())", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 716, in to_yaml", 
        "    return cfn_flip.to_yaml(self.to_json(), clean_up=clean_up,", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 712, in to_json", 
        "    return json.dumps(self.to_dict(), indent=indent,", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 663, in to_dict", 
        "    return encode_to_dict(t)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 66, in encode_to_dict", 
        "    props[name] = encode_to_dict(prop)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 66, in encode_to_dict", 
        "    props[name] = encode_to_dict(prop)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 57, in encode_to_dict", 
        "    return encode_to_dict(obj.to_dict())", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/__init__.py\", line 247, in to_dict", 
        "    self.validate()", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/cloudwatch.py\", line 94, in validate", 
        "    exactly_one(self.__class__.__name__, self.properties, conds)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/troposphere/validators.py\", line 227, in exactly_one", 
        "    class_name, ', '.join(conditionals)))", 
        "ValueError: Alarm: one of the following must be specified: ExtendedStatistic, Statistic"
    ],

**Comment by girishkhadke** [comment]
Statistic/ExtendedStatistic are optional when "Metric" attribute is specified.

**Comment by axelpavageau** [comment]
Hello, 
That's not what the doc currently says : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-extendedstatistic
Is is wrong ?

**Comment by girishkhadke** [comment]
Yes. Document is wrong.   The exactly_once check on Alarms baseAWS object is checking if either Extendedstatistic or Statistic is set. 

When I normally use a YAML template without "Statistic" or "ExtendedStatistic" attribute for an alarm based on metric expression, CFN deployment works.

**Comment by axelpavageau** [comment]
The API doc (https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html) is ambiguous : 

> When you call PutMetricAlarm and specify a MetricName, you must specify either Statistic or ExtendedStatistic, but not both.

but it doesn't explicit whether one of those properties is mandatory when MetricName is not specified

**Comment by girishkhadke** [comment]
Yes..Document is ambiguous ...but check their sample request:

`{
    "AlarmActions": [
        "arn:aws:sns:us-west-1:123456789012:my_sns_topic",
        "arn:aws:sns:us-west-1:123456789012:my_other_sns_topic"
    ],
    "ComparisonOperator": "GreaterThanThreshold",
    "EvaluationPeriods": 3,
    "Threshold": 40,
    "AlarmDescription": "MyService Aggregate Connection Error Rate (Alarm at 3%)",
    "AlarmName": "MyService Connection Error Rate",
    "Metrics": [
        {
            "MetricStat": {
                "Metric": {
                    "MetricName": "ConnectionsFailed",
                    "Namespace": "MyService"
                },
                "Period": 60,
                "Stat": "Sum"
            },
            "Id": "m1",
            "ReturnData": "False"
        },
        {
            "MetricStat": {
                "Metric": {
                    "MetricName": "ConnectionsDropped",
                    "Namespace": "MyService"
                },
                "Period": 60,
                "Stat": "Sum"
            },
            "Id": "m2",
            "ReturnData": "False"
        },
        {
            "MetricStat": {
                "Metric": {
                    "MetricName": "RequestsThrottled",
                    "Namespace": "MyService"
                },
                "Period": 60,
                "Stat": "Sum"
            },
            "Id": "m3",
            "ReturnData": "False"
        },
        {
            "MetricStat": {
                "Metric": {
                    "MetricName": "ConnectionAttempts",
                    "Namespace": "MyService"
                },
                "Period": 60,
                "Stat": "Sum"
            },
            "Id": "m4",
            "ReturnData": "False"
        },
        {
            "Id": "error_total",
            "Expression": "m1+m2+m3",
            "ReturnData": "False"
        },
        {
            "Id": "error_rate",
            "Expression": "(error_total/m4)*100",
            "ReturnData": "True",
            "Label": "Total Connection Error Rate"
        }
    ]
}`

**Comment by girishkhadke** [comment]
Right now for a workaround I am using : validation=False to skip validation of properties and it works.

```
self.add_resource(cloudwatch.Alarm(
            "vipOidcVIPConfigTableConsumedReadThroughputAlarmWarn",
            ActionsEnabled=True,
            AlarmActions=[
                self.monitoring_exports("VipOidcAppInfraWarnSnsTopicArn"),
            ],
            AlarmDescription=self.sub_table_name("OIDC ${AWS::Region} ${vpcEnvironment} ${serviceEnvironment} DynamoDB table ${tableName} has ConsumedReadThroughput >= ${readCapacityUnitsThreshold} for 60s.", "VIPConfigTableName"),
            AlarmName=self.sub_table_name("RU-W-DynamoDB-OIDC ConsumedReadThroughput >= ${readCapacityUnitsThreshold}-${tableName}", "VIPConfigTableName"),
            ComparisonOperator="GreaterThanOrEqualToThreshold",
            EvaluationPeriods="1",
            Metrics=[
                cloudwatch.MetricDataQuery(
                    Id=self.sub_table_name("${tableName}_ConsumedReadCapacityUnits", "VIPConfigTableName"),
                    Label=self.sub_table_name("${tableName}_ConsumedReadCapacityUnits", "VIPConfigTableName"),
                    MetricStat=cloudwatch.MetricStat(
                        Metric=cloudwatch.Metric(
                            Dimensions=[
                                cloudwatch.MetricDimension(
                                    Name="TableName",
                                    Value=self.dynamodb_exports("VIPConfigTableName")
                                ),
                            ],
                            MetricName="ConsumedReadCapacityUnits",
                            Namespace="AWS/DynamoDB"
                        ),
                        Period="60",
                        Stat="Sum",
                        Unit="Count",
                    ),
                    ReturnData="true",
                ),
                cloudwatch.MetricDataQuery(
                    Id=self.sub_table_name("${tableName}_ConsumedReadThroughput", "VIPConfigTableName"),
                    Label=self.sub_table_name("${tableName}_ConsumedReadThroughput", "VIPConfigTableName"),
                    Expression=self.sub_table_name("${tableName}_ConsumedReadCapacityUnits/PERIOD(${tableName}_ConsumedReadCapacityUnits)", "VIPConfigTableName"),
                    ReturnData="false",
                ),
            ],
            Threshold=Ref(self.read_capacity_units_threshold),
            TreatMissingData="notBreaching",
            validation=False,
        ))

        self.add_resource(cloudwatch.Alarm(
            "vipOidcVIPConfigTableConsumedWriteThroughputAlarmWarn",
            ActionsEnabled=True,
            AlarmActions=[
                self.monitoring_exports("VipOidcAppInfraWarnSnsTopicArn"),
            ],
            AlarmDescription=self.sub_table_name("OIDC ${AWS::Region} ${vpcEnvironment} ${serviceEnvironment} DynamoDB table ${tableName} has ConsumedWriteThroughput >= ${writeCapacityUnitsThreshold} for 60s.", "VIPConfigTableName"),
            AlarmName=self.sub_table_name("RU-W-DynamoDB-OIDC ConsumedWriteThroughput >= ${writeCapacityUnitsThreshold}-${tableName}", "VIPConfigTableName"),
            ComparisonOperator="GreaterThanOrEqualToThreshold",
            EvaluationPeriods="1",
            Metrics=[
                cloudwatch.MetricDataQuery(
                    Id=self.sub_table_name("${tableName}_ConsumedWriteCapacityUnits", "VIPConfigTableName"),
                    Label=self.sub_table_name("${tableName}_ConsumedWriteCapacityUnits", "VIPConfigTableName"),
                    MetricStat=cloudwatch.MetricStat(
                        Metric=cloudwatch.Metric(
                            Dimensions=[
                                cloudwatch.MetricDimension(
                                    Name="TableName",
                                    Value=self.dynamodb_exports("VIPConfigTableName")
                                ),
                            ],
                            MetricName="ConsumedWriteCapacityUnits",
                            Namespace="AWS/DynamoDB"
                        ),
                        Period="60",
                        Stat="Sum",
                        Unit="Count",
                    ),
                    ReturnData="true",
                ),
                cloudwatch.MetricDataQuery(
                    Id=self.sub_table_name("${tableName}_ConsumedWriteThroughput", "VIPConfigTableName"),
                    Label=self.sub_table_name("${tableName}_ConsumedWriteThroughput", "VIPConfigTableName"),
                    Expression=self.sub_table_name("${tableName}_ConsumedWriteCapacityUnits/PERIOD(${tableName}_ConsumedWriteCapacityUnits)", "VIPConfigTableName"),
                    ReturnData="false",
                ),
            ],
            Threshold=Ref(self.write_capacity_units_threshold),
            TreatMissingData="notBreaching",
            validation=False,
        ))
```

**Comment by axelpavageau** [comment]
Ok. I've opened #1276 with a fix proposal. Let me know what you think about it.

**Pull request merged**
