### PR TITLE
Completed AWS SAM support

### PR DESCRIPTION
**Pull request by Noah-Huppert**
@dogonthehorizon did almost all the heavy lifting for this one. I fixed the bug mentioned in the previous PR #671.

I did this by adding a `cls` argument to the `TemplateGenerator._convert_definition` method. If the `cls` argument is provided it will attempt to create an instance of the provided class. If it is not provided then no classes will be made.

Then the only place where this `cls` argument is provided is in the `TemplateGenerator.__init__` method when adding resources.

All the tests pass but I am suspicious of my fix, it seemed too simple for such and annoying bug.

### CODE REVIEW

**Comment by Noah-Huppert** [comment]
Looks like I got to fix some code style.

**Comment by Noah-Huppert** [comment]
Ok that's fixed

**Comment by dogonthehorizon** [comment]
Hey @Noah-Huppert, awesome to see this work carried forward. Nice work! :D

**Comment by markpeek** [comment]
Nice job @Noah-Huppert and @dogonthehorizon! Thank you for getting SAM implemented.

**Comment by Noah-Huppert** [comment]
When about do you think this will make it into a release?

**Comment by markpeek** [comment]
I'm trying to wrangle a few remaining PR's into master. More than likely I'll do a new release over the weekend.

**Comment by johnculkin** [comment]
Awesome - looking forward to the release

**Comment by juliensimon** [comment]
Not involved with the project, but maybe talking to this guy would make sense ? https://github.com/capless/sammy

**Comment by Noah-Huppert** [comment]
Unfortunately we already added all of the SAM resources so it wouldn't make much sense to redo it again but using a library

**Pull request merged**
