### PR TITLE
FromPort, ToPort and Egress are optional

### PR DESCRIPTION
**Pull request by muikrad**
Those 3 properties are flagged as optional in AWS's docs.

### CODE REVIEW

**Comment by muikrad** [comment]
#392

**Comment by muikrad** [comment]
Ow, sorry, I'm a total noob with github, I wanted to do a different PR with this last change; I'll be more careful next time.

**Comment by markpeek** [comment]
@muikrad It would be best to back out the more global import changes from this PR and keep these issues separate. If there is a dependency issue you're worried about then I'll merge #463 first (just the port changes) and then you can apply your import change on top. Thanks.

**Comment by muikrad** [comment]
@markpeek Sorry I'm learning github TODAY :sob: I reverted the last change which wasn't supposed to be in here at all (import_cloudformation). Do you want to merge the trivial AWSHelperFn removals from or should I (learn more github and...) revert and move that to a separate commit?

**Comment by markpeek** [comment]
@muikrad I pulled out the port changes and the AWSHelperFn as separate commits after squashing things. Please check out and approve the two commits in this branch to make sure I got the right changes: https://github.com/cloudtools/troposphere/tree/muikrad-463

BTW, for forked projects I find it best to create non-master branches to handle PR's. That way you can always sync the real master back into your forked repo.

**Comment by muikrad** [comment]
It looks OK to me.

Sorry for the fiasco and thanks for the help and advice.

**Comment by markpeek** [comment]
The port changes and the AWSHelperFn have been pushed onto master as separate commits. Thanks for the changes!

**Pull request closed without merging**
