### PR TITLE
Update ecs.py

### PR DESCRIPTION
**Pull request by msirull**
Add deployment configuration (for rolling updates) to ECS per:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-taskdefinition
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentconfiguration.html

### CODE REVIEW

**Comment by msirull** [comment]
Untested, first PR for Troposphere. Hopefully I got the structure right  👍

**Comment by ldenman** [comment]
Nice, looks like it passed the tests. :+1:

**Comment by philtay** [comment]
Duplicate of https://github.com/cloudtools/troposphere/pull/471

**Comment by markpeek** [comment]
Closing - Duplicate of #471

**Pull request closed without merging**
