### PR TITLE
Adding AWS::ResourceGroups::Group resource, per March 19, 2020 update

### PR DESCRIPTION
**Pull request by axelpavageau**
implements #1627

### CODE REVIEW

**Comment by PatMyron** [comment]
@axelpavageau are these programattically generated? If so, how?
https://github.com/cloudtools/troposphere/issues/1626
https://github.com/cloudtools/troposphere/issues/1627
https://github.com/cloudtools/troposphere/issues/1628
https://github.com/cloudtools/troposphere/issues/1629
https://github.com/cloudtools/troposphere/issues/1630
https://github.com/cloudtools/troposphere/issues/1631
https://github.com/cloudtools/troposphere/issues/1632
https://github.com/cloudtools/troposphere/issues/1633
https://github.com/cloudtools/troposphere/issues/1634
https://github.com/cloudtools/troposphere/issues/1635
https://github.com/cloudtools/troposphere/issues/1636
https://github.com/cloudtools/troposphere/issues/1637
https://github.com/cloudtools/troposphere/issues/1638
https://github.com/cloudtools/troposphere/issues/1639
https://github.com/cloudtools/troposphere/issues/1640
https://github.com/cloudtools/troposphere/pull/1641
https://github.com/cloudtools/troposphere/pull/1642
https://github.com/cloudtools/troposphere/pull/1643
https://github.com/cloudtools/troposphere/pull/1644
https://github.com/cloudtools/troposphere/pull/1645
https://github.com/cloudtools/troposphere/pull/1646
https://github.com/cloudtools/troposphere/pull/1647
https://github.com/cloudtools/troposphere/pull/1648
https://github.com/cloudtools/troposphere/pull/1649
https://github.com/cloudtools/troposphere/pull/1650
https://github.com/cloudtools/troposphere/pull/1651
https://github.com/cloudtools/troposphere/pull/1652
https://github.com/cloudtools/troposphere/pull/1653

**Comment by axelpavageau** [comment]
Nope, manual entry.

**Comment by markpeek** [comment]
@axelpavageau @PatMyron This is how I do my auto-generation:
```
$ make spec2
...
Downloaded version: "14.1.0"
$ gen () {
>   name=${1:none}
>   python scripts/gen.py --name $name CloudFormationResourceSpecification.json
> }
$ gen resourcegroups
```

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
