### PR TITLE
fix json output for AWS::Logs::Destination

### PR DESCRIPTION
**Pull request by drmaples**
use correct base class for `Destination`. needs to be `AWSObject`

- the output for destination should be nested under `Property`, using the correct base class achieves this.
- issue cloudtools/troposphere#481

### CODE REVIEW

**Comment by markpeek** [comment]
Duplicate fix.

**Comment by markpeek** [comment]
Reopening if you want to rebase and add the new test.

**Comment by drmaples** [comment]
@markpeek rebased

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
