### PR TITLE
Fix typo in S3_Bucket.py example

### PR DESCRIPTION
**Pull request by davemasino**
Changed EC2 instance to S3 Bucket in description

### CODE REVIEW

**Comment by davemasino** [comment]
Hmmm I noticed a CI test failed. Maybe it's because I edited a typo in the description?

**Comment by markpeek** [comment]
The output needs to be updated in the PR as well. Look [here](https://github.com/cloudtools/troposphere/blob/master/tests/examples_output/S3_Bucket.template).

**Comment by davemasino** [comment]
Thanks Mark. Fixed.

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
