### PR TITLE
add true s3 bucket name validator

### PR DESCRIPTION
**Pull request by ryno75**
Added a validator for s3 bucket names to get past the basestring (alphanumeric) limitation.  Used a regex to handle that.
Also... added a validator test for the new s3_bucket_name validator.

### CODE REVIEW

**Comment by markpeek** [comment]
Thank you for implementing this patch. I noticed your regex allows for 255 character "non-dns-compliant" bucket names. Should this validator really enforce the DNS compliant naming?
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

Also, I saw you removed a negative test. I think what you want is:
```
with self.assertRaises(ValueError):
    s3_bucket_name('!invalid_bucket')
```

**Comment by ryno75** [comment]
Oh, yeah... nice catch on the DNS compliancy... I forgot to change that from the standard bucket name length to the DNS compliant length.  While the cloudformation docs aren't clear, I wouldn't be surprised if the stack create choked on bucket names longer than 63 chars too.

Yeah, I think you are right on the negative test.  I didn't even consider using the double-neg like that.

Shall I implement these changes and re-create the pull request?

**Comment by markpeek** [comment]
That would be great if you could commit and push those changes (it should automatically update this pull request). For extra credit on testing you could add things like this to validate the bounds checking:

```
s3_bucket_name('a' * 63)
s3_bucket_name('a' * 3)
with self.assertRaises(ValueError):
    s3_bucket_name('aa')
with self.assertRaises(ValueError):
    s3_bucket_name('a' * 64)
```

**Comment by ryno75** [comment]
Ok. Challenge accepted. ;-)  Have a look.

**Comment by markpeek** [comment]
Looks great. Thanks!

**Pull request merged**
