### PR TITLE
Added EC2 Nat Gateway resource

### PR DESCRIPTION
**Pull request by jarosser06**
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html

cc @martinb3

### CODE REVIEW

**Comment by mwarkentin** [comment]
So excited.. :godmode:

**Comment by tfeak** [comment]
Thank you for this. 

Though, the Route resource will also need updating for this to be useful. They've added a NatGatewayId property to allow you to add the Nat to your route tables.

**Comment by jarosser06** [comment]
I'll take a look and add that change as well.

**Comment by martinb3** [comment]
I went to the docs for AWS::EC2::Route and added the missing field, and verified there weren't any others missing. This should be good to go.

**Comment by DaveHewy** [comment]
LGTM. Maybe some example usage in examples/ ?

**Comment by jarosser06** [comment]
Added an example in examples.

**Comment by phobologic** [comment]
Awesome - so ready to nuke my NAT boxes.  Thanks @jarosser06!

**Comment by phobologic** [comment]
Thanks!

**Pull request merged**
