### PR TITLE
Added ECS ProxyConfiguration, DependsOn,  StartTimeout and StopTimeout parameters

### PR DESCRIPTION
**Pull request by cigan1**
Also added other new parameters such as: ProxyConfiguration for TaskDefinition and  DependsOn, StartTimeout and StopTimeout for ContainerDefinition.

### CODE REVIEW

**Comment by cigan1** [comment]
@markpeek hey, could you please merge this pull request? Anything else I need to do? Thanks, Yoni.

**Comment by markpeek** [comment]
I don't see that these changes are in the documentation or released to CloudFormation yet. Holding pending release.

**Comment by markpeek** [comment]
lol! I see I opened issue #1378 to track adding these changes. While the spec files tend to lag, I'm surprised the documentation isn't reflecting these additions.

**Comment by cigan1** [comment]
That's so strange I can see what you are saying but I swear I've seen this in the release notes about a week ago and obviously I read the documentation in order to code this. Will investigate tomorrow. Thanks.

**Pull request merged**
