### PR TITLE
Test Python 3.5

### PR DESCRIPTION
**Pull request by philtay**

### CODE REVIEW

**Comment by philtay** [comment]
The tests fail for reasons unrelated to this PR.

**Comment by markpeek** [comment]
What is odd is the traceback for test_EC2Conditions shows awacs::test_examples.py.

**Comment by philtay** [comment]
Even more odd is the fact that it works on Python 2...

**Comment by philtay** [comment]
@markpeek fixed

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
