### PR TITLE
Update Export param

### PR DESCRIPTION
**Pull request by cb17**
Update Export param to use Export(string) instead of dict

### CODE REVIEW

**Comment by cb17** [comment]
BTW, sorry for the delay on this, it's been a busy week.

I used the standard pattern of creating a helper function, but is there a better way so you can just pass in a string instead of Export(str)?

**Comment by markpeek** [comment]
Thanks!

**Comment by cristian04** [comment]
According to Cloudformation documentation, the export parameter looks like this:

"Export" : {
      "Name" : {"Fn::Sub": "${AWS::StackName}-VPCID" }
    }

How can I do the same with troposphere now that the value is a String?

**Comment by markpeek** [comment]
This was discussed in #610. Use:
```
Export=Export("string")
```

**Pull request merged**
