### PR TITLE
Run tests against Python 3.9

### PR DESCRIPTION
**Pull request by michael-k**
3.9.0 final is [expected](https://www.python.org/dev/peps/pep-0596/#schedule) on Monday, 2020-10-05.

### CODE REVIEW

**Comment by markpeek** [comment]
Thanks!

**Comment by PatMyron** [comment]
@markpeek @michael-k Travis doesn't seem to be running at all for PRs

**Comment by michael-k** [comment]
I can see some builds here: https://travis-ci.org/github/cloudtools/troposphere/pull_requests

But I'm not a big fan of Travis CI any more since they've let go many of their staff a while ago.  Should I prepare a PR to switch to GitHub Actions?  I've had great experiences with that so far.

#1814 probably errored because the PR was merged before it was able to start?

**Comment by PatMyron** [comment]
@michael-k interesting, so Travis does seem to be running for PRs, but the results don't seem to show in PRs themselves

**Comment by PatMyron** [comment]
[results showing in PRs as of this week](https://github.com/cloudtools/troposphere/pull/1844#issuecomment-738909401)

**Comment by michael-k** [comment]
Should we switch to GitHub Actions?  So far I've only had positive experiences with it.

**Pull request merged**
