### PR TITLE
Add LambdaPermission in Example CloudWatchEventsSample.py

### PR DESCRIPTION
**Pull request by fdmsantos**
It's necessary Create Permission in CloudWatchEventsSample.py Example to Lambda to work.

### CODE REVIEW

**Comment by markpeek** [comment]
This commit needs to include the output [here](https://github.com/cloudtools/troposphere/blob/master/tests/examples_output/CloudWatchEventsSample.template).

**Comment by fdmsantos** [comment]
Hi @markpeek I have updated the output file.

Thanks

**Comment by phobologic** [comment]
Hey @fdmsantos - it appears that this is still failing tests.  Please check out the test output and try to resolve it, thanks!

**Comment by fdmsantos** [comment]
hi @phobologic ,

It's fine now.

Thanks.

**Pull request merged**
