### PR TITLE
AWS::MWAA Adding for managed airflow

### PR DESCRIPTION
**Pull request by adam133**
For this issue: https://github.com/cloudtools/troposphere/issues/1855
My first time contributing to this library, so I'm guessing I'm missing some things. But hopefully someone can use this as a starting point or at least check that I added things correctly!

### CODE REVIEW

**Comment by adam133** [comment]
Created to close this issue: https://github.com/cloudtools/troposphere/issues/1855

**Comment by adam133** [comment]
Needs some work yet - I'm missing some required parameters. Update incoming.

**Comment by adam133** [comment]
Just wanted to share that using this PR locally I was able to create a cloudformation stack with a MWAA environment, so it seems like it works. Might be good to add more validation when I get time though. For example, the source bucket name has to start with `airflow-`, and there is a minimum of two subnets for the security group.

**Comment by markpeek** [comment]
Since this change was written for Python3 (str instead of basestring), I'll merge this in as part of the 3.0.0 release.

**Comment by markpeek** [comment]
Thanks!

**Pull request merged**
