### PR TITLE
status required and managedpolicyarns

### PR DESCRIPTION
**Pull request by iblazevic**
*status is required http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html
* tests for validators
*adding managedPolicyArns

### CODE REVIEW

**Comment by iblazevic** [comment]
Not sure about 'ManagedPolicyArns' I wasn't using them, should they maybe be some other type or just a plain string

**Comment by markpeek** [comment]
I was wondering the same thing. I'm guessing both a string (basestring) and Ref() of a ManagedPolicy object. The Ref() should be handled implicitly but I'll have to test it later.

**Comment by iblazevic** [comment]
Do you want me to pull it out of this PR and update status and tests until this is figured out?

**Comment by markpeek** [comment]
Thanks for the offer. Just leave it in for now.

**Comment by markpeek** [comment]
I wrote a quick test and ManagedPolicy looks good to me. Thanks for the pull request.

**Pull request merged**
