### PR TITLE
WIP : Adding new AWS::Greengrass resource, per 2019 March 15 update

### PR DESCRIPTION
**Pull request by axelpavageau**

### CODE REVIEW

**Comment by axelpavageau** [comment]
@markpeek I have a question on this one : Greengrass has both a `AWS::Greengrass::SubscriptionDefinitionVersion` object and a `SubscriptionDefinitionVersion` property for `AWS::Greengrass::SubscriptionDefinition`. How would you like to handle that ?

**Comment by markpeek** [comment]
Sorry for the delay as I missed seeing the tagged question. I've commented to AWS about this issue in the past but it still seems to occur. I believe I've been trying to standardize on adding "Property" at the end for the property one.

Also, I'm not sure how you generate new resources but I just moved over my WIP generator update into master. This can be run with:
```
# Update the spec file
make spec2
# Generate the greengrass troposphere file
python scripts/gen.py --name greengrass CloudFormationResourceSpecification.json
```
Looks like it doesn't handle the duplicate well right now but it might help eliminate some typing.

**Comment by mneil** [comment]
Any progress on this? Something I can help finish off to get it merged?

**Comment by markpeek** [comment]
@mneil I just auto-generated this greengrass code for you to try:
https://github.com/cloudtools/troposphere/commit/f73c855dcfb891900e23868e903e7c81abe3d35e

**Comment by mneil** [comment]
So far so good! It's missing 1 thing. I noticed this because I brought it up with the (unrelated) cfn-lint project as well. The `AWS::Greengrass::ResourceDefinition` is missing. It's not in the current spec but it is a valid resource:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-greengrass-resourcedefinition.html

I can try writing this one in manually for now - it's a fairly straightforward resource like the others that were already generated.

**Comment by markpeek** [comment]
Nice find. I'll ping a contact on the CF team to see if they know about it not being in the spec files.

**Comment by mneil** [comment]
I've added in the resource definition and verified the resources all create / work as expected. Should I add tests and open a separate PR or do you need to wait until they add this to the spec?

**Comment by markpeek** [comment]
@mneil merged updated greengrass support into master. Thanks @axelpavageau for the initial PR.

**Pull request closed without merging**
