### PR TITLE
Raise ValueError for Outputs and Mappings - Fix Issue #732

### PR DESCRIPTION
**Pull request by apmclean**
Raises ValueError when CloudFormation template limits are reached for Outputs or Mappings.

Test cases included and passing.

Thanks!

### CODE REVIEW

**Comment by apmclean** [comment]
Ok let me tune the tests up.  I followed the existing test case paradigm for parameters and resources which have the maximums hard-coded for their ValueError.  Do you want me to include a tune-up for those in the pull request too?

**Comment by markpeek** [comment]
Ah, got it. Guess we didn't catch it before. Yes, if you're so inclined please tune-up the other ones as well. Thanks!

**Comment by apmclean** [comment]
Would it make sense to expose the template limit maximums as attributes of the template class?  Then the test cases could determine them programmatically.

Within the Template class init something like:

```python
self.limits={
    'outputs': 60,
    'resources': 200,
    'parameters': 100,
    'mappings': 100
}
```

Then any future changes will just require changing the class versus the class + test cases.

**Comment by markpeek** [comment]
Interesting idea. But I'm not sure if those would be used except for the test cases. Probably best not to clutter the template class with it at this time.

**Comment by apmclean** [comment]
Understood.  Cleaned up the test case and passed flakes and codestyle.

Thanks again for a great tool!  I'll try to contribute in more meaningful ways in the future.

**Comment by markpeek** [comment]
Excellent. Thank you for the contribution and fixing those additional tests.

**Pull request merged**
