### PR TITLE
Adding VPC endpoint support

### PR DESCRIPTION
**Pull request by pas256**
This PR adds support for VPC endpoints as per the documentation here:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

### CODE REVIEW

**Comment by pas256** [comment]
@markpeek Not sure how busy you are, but I sure would appreciate a new release of troposphere once this is merged. I need it for a consulting client next week. Thanks mate!

**Comment by pas256** [comment]
Actually, I'll close this PR and let's use #304 as @kalefranz got there first with the full implementation.

**Comment by markpeek** [comment]
@pas256 Due to a vacation I'm a bit behind in consolidating the various pull requests and other changes. I'll try to get out a new release before the end of day tomorrow. Cheers.

**Comment by pas256** [comment]
You rock!

**Pull request closed without merging**
