### PR TITLE
Adding HealthCheckGracePeriodSeconds into ECS Service

### PR DESCRIPTION
**Pull request by andydoTech**
https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ecs-adds-elb-health-check-grace-period/

### CODE REVIEW

**Comment by phobologic** [comment]
I don't see this mentioned in the Cloudformation docs yet:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html

Are you sure this is accepted by Cloudformation?

**Comment by phobologic** [comment]
It's also not currently listed in the resource schema specification:

https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

**Comment by andydoTech** [comment]
Ah, you are right. Let me close and submit it when they are ready.

**Comment by phobologic** [comment]
Looks like this was added, and we have another PR for it: #971 :)

**Comment by phobologic** [comment]
Re-opening since this should be good now, thanks @andydoTech !

**Comment by phobologic** [comment]
Ok, made a minor ordering change, but I'm going to accept this now.  Thanks @andydoTech !

**Pull request merged**
