### PR TITLE
Add to_dict method for Template.

### PR DESCRIPTION
**Pull request by wt**

### CODE REVIEW

**Comment by rcuza** [comment]
The change itself appears to an elegant way to get a dictionary output, but there is a problem.

I took a stab at creating a test for the `to_dict()` method. It is a simplistic hack of the `test_exclusive` test in `test_dict.py`. What I was going for is "dict_in -> troposphere.objects -> dict_out, assertDictEquals(dict_in, dict_out)".

Here is the code:
```
    def test_exclusive_dict(self):
        d = {
            "Cpu": 1,
            "Environment": [
                {
                    "Name": "REGISTRY_STORAGE",
                    "Value": "s3"
                },
                {
                    "Name": "REGISTRY_STORAGE_S3_REGION",
                    "Value": "eu-west-1"
                }
            ],
            "Essential": True,
            "Image": "registry:2",
            "Memory": 500,
            "Name": "registry",
            "PortMappings": [
                {
                    "ContainerPort": 5000,
                    "HostPort": 5000
                },
                {
                    "ContainerPort": 5001,
                    "HostPort": 5001
                }
            ]
        }

        t = Template()
        cd = ecs.ContainerDefinition.from_dict("mycontainer", d)
        td = ecs.TaskDefinition(
                "taskdef",
                ContainerDefinitions=[cd],
                Volumes=[ecs.Volume(Name="myvol")],
        )
        t.add_resource(td)
        d_out = t.to_dict()
        self.assertDictEqual(d, d_out)
```

And here is the failed output:
```======================================================================
FAIL: test_exclusive_dict (tests.test_dict.TestDict)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/raulcuza/dev/rac/troposphere/tests/test_dict.py", line 84, in test_exclusive_dict
    self.assertDictEqual(d, d_out)
AssertionError: {'PortMappings': [{'ContainerPort': 5000, 'HostPort': 5000}, {'ContainerPort': 5 [truncated]... != {'Resources': {'taskdef': <troposphere.ecs.TaskDefinition object at 0x10f40bbd0> [truncated]...
+ {'Resources': {'taskdef': <troposphere.ecs.TaskDefinition object at 0x10f40bbd0>}}
- {'Cpu': 1,
-  'Environment': [{'Name': 'REGISTRY_STORAGE', 'Value': 's3'},
-                  {'Name': 'REGISTRY_STORAGE_S3_REGION', 'Value': 'eu-west-1'}],
-  'Essential': True,
-  'Image': 'registry:2',
-  'Memory': 500,
-  'Name': 'registry',
-  'PortMappings': [{'ContainerPort': 5000, 'HostPort': 5000},
-                   {'ContainerPort': 5001, 'HostPort': 5001}]}

----------------------------------------------------------------------
Ran 194 tests in 0.267s

FAILED (failures=1)
```

If my test is correct, and I am not sure that it is correct, then it appears to be saying this change wont work. The troposphere objects deeper in the template object are not getting translated to dictionary objects.

**Comment by rcuza** [comment]
As is, this doesn't look good to me. 👎

**Comment by dmotles** [comment]
You could cheat by doing this:

```python
def to_dict(self):
    return json.loads(self.to_json())
```

but that's kind of dirty :)

**Comment by phobologic** [comment]
@wt Any chance you've gotten to look @ @rcuza 's comments?  It also appears that this now has conflicts with other more recent changes.

**Pull request closed without merging**
