### PR TITLE
Auto-generate WAFv2

### PR DESCRIPTION
**Pull request by markpeek**
Here is a first pass at auto-generating WAFv2. Wanted to get some input on this change as there were quite a few backward compatibility changes needed along with some removed properties and changes to required fields.

@dalgarin @jerry153fish @axelpavageau @marksidell

### CODE REVIEW

**Review by jerry153fish — APPROVED** [review]
LGTM

**Review by sid21rane — CHANGES_REQUESTED** [review]
Please can we include LabelMatchStatement for WebACL and Rulegroup as in -

AWS::WAFv2::WebACL -https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-labelmatchstatement.html

AWS::WAFv2::RuleGroup -https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-labelmatchstatement.html

**Comment by markpeek** [comment]
@sid21rane LabelMatchStatement is included in this PR via StatementOne, StatementTwo and StatementThree properties. These are used due to the circular definitions in WAFv2 and are implemented per [AWS::WAFv2::RuleGroup Statement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-statement.html).

**Comment by sid21rane** [comment]
Thanks Mark,

Please can I request for LabelMatchStatement under StatementOne, Two and
Three for AWS::WAFv2::WebACL as well.


Regards,
Siddharth Rane

**Comment by markpeek** [comment]
@sid21rane yes, as I commented above LabelMatchStatement is already in each of those classes for this PR.

**Comment by markpeek** [comment]
Oh, sorry, misunderstood your request. WebACL and RuleGroup use a common set of Statements so it is already there. There are additions to the WebACL version which I took care of this morning.

**Comment by sid21rane** [comment]
Great then. Thanks Mark. When can we expect the PR to go live?


Regards,
Siddharth Rane

**Comment by sid21rane** [comment]
Thanks for the changes Mark, can see the attribute now on the doc.
Appreciate it.


regards,
Siddharth Rane

**Pull request merged**
