### PR TITLE
Update not create

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
Working with @markfalk discovered its easier to use this script if it has an update option.  This change includes these updates while maintaining backwards compatibility:

- Can now use `-u` or `--update` to trigger a cfn update action instead of a create action
- Fixes pep8 trailing whitespace
- Fixes pep8 line length to be < 80 chars

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
Friendly ping - Hoping to get a review on this PR.

**Comment by chrisgilmerproj** [comment]
Merged this with master, I think its ready to review.

**Comment by markpeek** [comment]
Thanks!

**Comment by chrisgilmerproj** [comment]
Thank you!

**Pull request merged**
