### PR TITLE
[Carry #1136] Return real booleans in the output

### PR DESCRIPTION
**Pull request by michael-k**
This picks up the work done by @ikben in PR cloudtools/troposphere#1136, addresses the merge conflict by rebasing and fixes the failing tests.

### CODE REVIEW

**Comment by michael-k** [comment]
Commit  62fbe39 should not have passed the tests.  I've tried that before: https://travis-ci.com/michael-k/troposphere/builds/113547741
Maybe I've pushed the last commit to fast and travis got confused. `¯\_(ツ)_/¯`

**Comment by ikben** [comment]
Feel free to squash all the commits together, there's nothing ground-breaking in mine :)

**Comment by markpeek** [comment]
Waiting on review/approval from @phobologic

**Comment by phobologic** [comment]
This looks good to me from a code perspective - but I'm curious what we should do to make sure folks aren't freaked out if suddenly a bunch of their stacks start updating?

The other question I have is whether or not json's booleans are actually case sensitive?  This page makes me think they are:

https://json-schema.org/understanding-json-schema/reference/boolean.html

**Comment by michael-k** [comment]
> The other question I have is whether or not json's booleans are actually case sensitive?

Yes, they are.

Python:
```python
import json

json.loads("true")  # True
json.loads("True")  # JSONDecodeError
```

Javascript:
```javascript
JSON.parse("true")  # true
JSON.parse("True")  # SyntaxError
```

**Comment by phobologic** [comment]
Ahh, sorry - my bad on the case sensitive question, I had flipped the cases between the python/resulting templates in my head somehow.  That looks good.

I waffle a little on punishing/scaring folks for not using cfn-lint.  Maybe a better way to roll this out would be to have this be sort of "Feature Flagged" with an environment variable or something, and only turn it on if that variable is set - then start using warnings to let folks know that this change is coming.  Then after a verison or two we can make it the default? What are you thoughts?

**Comment by michael-k** [comment]
Any suggestions regarding the naming of such a env var?

**Comment by phobologic** [comment]
I'm open to just about anything - `OUTPUT_REAL_BOOLEANS` maybe?

Also, don't take my suggestion as what *has* to happen :)  Just wanted to get some conversation started around it.  It seems like a nice compromise though, letting folks who want to use real booleans start using it while not penalizing folks who aren't ready for it.

Also curious around thoughts on throwing warnings to let folks know about the change so that we can encourage people to prepare.  @markpeek @michael-k

**Comment by markpeek** [comment]
Likely prefix for uniqueness: `TROPO_REAL_BOOL`? Is just an env var sufficient or do we need to add a function enablement as well? I do wonder if warnings are too invasive and we should communicate via release notes and the email list.

**Comment by michael-k** [comment]
I've added support for the env var `TROPO_REAL_BOOL`.  As you can see in the [`commits`](https://github.com/cloudtools/troposphere/pull/1409/commits) tab,

- tests are passing in commit 020cb83c683106a7a37f95c8eef814c229a4521e (env var not set = booleans as strings) and
- tests are also passing after adjusting the tests and setting the env var to `"true"` in commit 39c71b5294bfb7e6edefdfa9d9dc108d8cf3f8f7.

Is this good enough or does this need tests for the old behavior as well?

**Comment by phobologic** [comment]
This looks great to me.  Thanks @michael-k for seeing this through!

**Comment by markpeek** [comment]
Thank you @michael-k and @ikben!

**Pull request merged**
