### PR TITLE
Added support for ForwardConfig in Listener

### PR DESCRIPTION
**Pull request by yks0000**
For Issue: https://github.com/cloudtools/troposphere/issues/1554

### CODE REVIEW

**Comment by yks0000** [comment]
@markpeek Will you be able to review this please?

**Comment by markpeek** [comment]
I do not see this supported in CloudFormation yet. Thank you for the PR and I will verify/merge after AWS implements it.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-defaultactions.html

**Comment by yks0000** [comment]
Thanks @markpeek  Their API documentation has mentioned about ForwardConfig and I have tested that CFN template for Listener with ForwardConfig work perfectly.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#forward-actions


However, I agree to you and I have asked AWS to update the documentation. Will update this thread accordingly.

**Comment by parvez99** [comment]
Thanks @yks0000 for this update, this is something very useful for one of the projects I'm working on. 

@markpeek I think the document you shared has a mention of using ForwardConfig:

"TargetGroupArn
The Amazon Resource Name (ARN) of the target group. Specify only when Type is forward and you want to route to a single target group. To route to one or more target groups, use ForwardConfig instead. "

I think the documentation still needs to be properly updated but looks like a quick fix from AWS for now.

**Comment by yks0000** [comment]
AWS has opened a [issue here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/338) to track it publicly

**Comment by helloangely** [comment]
CloudFormation just updated their documentation to include ForwardConfig. Very excited about this!

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-forwardconfig.html

**Comment by aaronkvanmeerten** [comment]
I have tested this PR as well and it works great, very excited to see it merged soon.

**Comment by markpeek** [comment]
Thanks! Appreciate the wait for it to be supported. I'm going to follow up with a couple of adjustments.

**Pull request merged**
